dev-lang/rust: fix build issue with Rust 1.61.0
Fix build issues with Rust 1.61.0 when applying
gentoo-musl-target-specs.patch.

```
error[E0308]: mismatched types
 -->
 compiler/rustc_target/src/spec/aarch64_gentoo_linux_musl.rs:6:24
  |
6 |     base.llvm_target =
   "aarch64-gentoo-linux-musl".to_string();
  |     ---------------- ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  expected enum `Cow`, found struct `std::string::String`
  |     |
  |     expected due to the type of this binding
  |
  = note: expected enum `Cow<'static, str>`
           found struct `std::string::String`
```

Replace `to_string` with `into`.

Based on Gentoo commit 445f23597c942b087145b869ac588fc1c1eac759.