app-crypt/trousers: use correct file permissions
The security patch that was brought in has stricter permission checks
which cause the service to fail:
ERROR: TCSD config file (/etc/tcsd.conf) must be user/group root/tss
Set the expected file ownership and permissions.

https://github.com/kinvolk/Flatcar/issues/335